### ISSUE TITLE
Bootstrapping Net7: [AWS::Cognito::UserPoolDomain] is missing required property: domain

### ISSUE THREAD

**Issue by rrowlands** [aws-samples/websocket-chat-application#34]
Hey,

I am a pretty big beginner when it comes to dotnet development so pardon if I missed something obvious. I have the following dotnet sdks installed:

```
#infrastructure-net7>dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.302 [C:\Program Files\dotnet\sdk]
```

When I run the bootstrap command I get lots of warnings at the top

```
C:\Users\Rich\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\7.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstra
ctions.targets(4,5): warning : Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgr
ading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore t
his warning and attempt to run in this unsupported configuration at your own risk. [E:\dev\projects\odokonia\backend\infrastructure-net7\src\Infrastructure\Infrastruct
ure.csproj]
C:\Users\Rich\.nuget\packages\microsoft.extensions.dependencyinjection\7.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.targets(4,5): warni
ng : Microsoft.Extensions.DependencyInjection 7.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or
 later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this
unsupported configuration at your own risk. [E:\dev\projects\odokonia\backend\infrastructure-net7\src\Infrastructure\Infrastructure.csproj]
C:\Users\Rich\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\7.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.Abstra
ctions.targets(4,5): warning : Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgr
ading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore t
his warning and attempt to run in this unsupported configuration at your own risk. [E:\dev\projects\odokonia\backend\infrastructure-net7\src\Infrastructure\Infrastruct
ure.csproj]
C:\Users\Rich\.nuget\packages\microsoft.extensions.dependencyinjection\7.0.0\buildTransitive\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.targets(4,5): warni
ng : Microsoft.Extensions.DependencyInjection 7.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or
 later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this
unsupported configuration at your own risk. [E:\dev\projects\odokonia\backend\infrastructure-net7\src\Infrastructure\Infrastructure.csproj]
```

And then the build runs for a bit and then eventually fails with the following message:

```
Unhandled exception. System.Exception: Error: FrontendStack/UserPool/TestDomain/Resource [AWS::Cognito::UserPoolDomain] is missing required property: domain
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.Cognito.IUserPool._Proxy.AddDomain(String id, IUserPoolDomainOptions options)
   at Infrastructure.Stacks.FrontendStack..ctor(Construct scope, String id, FrontendStackProps props) in E:\dev\projects\odokonia\backend\infrastructure-net7\src\Infrastructure\Stacks\FrontendStack.cs:line 183
   at Infrastructure.Program.Main(String[] args) in E:\dev\projects\odokonia\backend\infrastructure-net7\src\Infrastructure\Program.cs:line 41

Subprocess exited with error 3762504530
```

Not sure if I'm using the wrong version of CDK? It wasn't specified in your guide so I just grabbed the latest

```
#infrastructure-net7>cdk --version
2.81.0 (build bd920f2)
```

**Comment by santatamas** [comment]
Hi! Have you specified a cognito domain prefix?

You can find that at #46 here:
infrastructure-net7/src/Infrastructure/Program.cs
