### ISSUE TITLE
Getting error "Subprocess exited with error 3762504530" while running cdk synth

### ISSUE THREAD

**Issue by ankushjain358** [aws-samples/websocket-chat-application#47]
`cdk synth` results in error as shown in the below screenshot.

![image](https://github.com/aws-samples/websocket-chat-application/assets/13661966/fbd19196-049c-44ed-b03f-33b5be274ed1)

## Steps to reproduce
1. Clone the repository.
2. cd `websocket-chat-application\infrastructure-net7`
3. Run `cdk synth`

**Comment by devsecopspaylouser** [comment]
I experience the same error as @ankushjain358 after a clean solution build with Docker Desktop up and running.

**Comment by santatamas** [comment]
This should be fixed now. Please pull the latest version and let me know how it goes :)

**Comment by ivanovvitaly** [comment]
I'm trying to walk through the CDK sample tutorial and getting the same error. 
steps:

- cdk init app --language csharp
- dotnet build src
- cdk synth or cdk list 

```
Unhandled exception. Amazon.JSII.Runtime.JsiiError: Child process exited unexpectedly!
   at Amazon.JSII.Runtime.Services.Runtime.ReadResponse()
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Hello()
   at Amazon.JSII.Runtime.Services.ServiceContainer.BuildServiceProvider(ILoggerFactory loggerFactoryOverride)
   at Amazon.JSII.Runtime.Services.ServiceContainer.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Amazon.JSII.Runtime.Services.ServiceContainer.get_ServiceProvider()
   at Amazon.JSII.Runtime.Deputy.JsiiTypeAttributeBase.Load(Assembly assembly)
   at Amazon.JSII.Runtime.Deputy.JsiiTypeAttributeBase.Load(Assembly assembly)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Stage..ctor(DeputyProps props)
   at Amazon.CDK.App..ctor(IAppProps props)
   at CdkWorkshop.Program.Main(String[] args) in C:\Development\cdk-workshop\src\CdkWorkshop\Program.cs:line 12
```

CDK version - 2.149.0 (build c8e5924)
npm version - 10.8.2
node version - v22.5.0
windows 11 - 22H2 (22621.3880)
dotnet sdks
6.0.424 [C:\Program Files\dotnet\sdk]
8.0.303 [C:\Program Files\dotnet\sdk]

please advice
